// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: protos/game.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateIntentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Dx            int32                  `protobuf:"varint,2,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy            int32                  `protobuf:"varint,3,opt,name=dy,proto3" json:"dy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateIntentMessage) Reset() {
	*x = StateIntentMessage{}
	mi := &file_protos_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateIntentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateIntentMessage) ProtoMessage() {}

func (x *StateIntentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateIntentMessage.ProtoReflect.Descriptor instead.
func (*StateIntentMessage) Descriptor() ([]byte, []int) {
	return file_protos_game_proto_rawDescGZIP(), []int{0}
}

func (x *StateIntentMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *StateIntentMessage) GetDx() int32 {
	if x != nil {
		return x.Dx
	}
	return 0
}

func (x *StateIntentMessage) GetDy() int32 {
	if x != nil {
		return x.Dy
	}
	return 0
}

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_protos_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_protos_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_protos_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerState) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerState) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type ClientGameJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGameJoin) Reset() {
	*x = ClientGameJoin{}
	mi := &file_protos_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGameJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGameJoin) ProtoMessage() {}

func (x *ClientGameJoin) ProtoReflect() protoreflect.Message {
	mi := &file_protos_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGameJoin.ProtoReflect.Descriptor instead.
func (*ClientGameJoin) Descriptor() ([]byte, []int) {
	return file_protos_game_proto_rawDescGZIP(), []int{2}
}

func (x *ClientGameJoin) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type ServerGameJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerState   *PlayerState           `protobuf:"bytes,1,opt,name=player_state,json=playerState,proto3" json:"player_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGameJoin) Reset() {
	*x = ServerGameJoin{}
	mi := &file_protos_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGameJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGameJoin) ProtoMessage() {}

func (x *ServerGameJoin) ProtoReflect() protoreflect.Message {
	mi := &file_protos_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGameJoin.ProtoReflect.Descriptor instead.
func (*ServerGameJoin) Descriptor() ([]byte, []int) {
	return file_protos_game_proto_rawDescGZIP(), []int{3}
}

func (x *ServerGameJoin) GetPlayerState() *PlayerState {
	if x != nil {
		return x.PlayerState
	}
	return nil
}

type ServerGameExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGameExit) Reset() {
	*x = ServerGameExit{}
	mi := &file_protos_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGameExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGameExit) ProtoMessage() {}

func (x *ServerGameExit) ProtoReflect() protoreflect.Message {
	mi := &file_protos_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGameExit.ProtoReflect.Descriptor instead.
func (*ServerGameExit) Descriptor() ([]byte, []int) {
	return file_protos_game_proto_rawDescGZIP(), []int{4}
}

func (x *ServerGameExit) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type ClientGameExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGameExit) Reset() {
	*x = ClientGameExit{}
	mi := &file_protos_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGameExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGameExit) ProtoMessage() {}

func (x *ClientGameExit) ProtoReflect() protoreflect.Message {
	mi := &file_protos_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGameExit.ProtoReflect.Descriptor instead.
func (*ClientGameExit) Descriptor() ([]byte, []int) {
	return file_protos_game_proto_rawDescGZIP(), []int{5}
}

type ClientEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ClientEvent_IntentMessage
	//	*ClientEvent_GameJoin
	//	*ClientEvent_GameExit
	Event         isClientEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_protos_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_protos_game_proto_rawDescGZIP(), []int{6}
}

func (x *ClientEvent) GetEvent() isClientEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ClientEvent) GetIntentMessage() *StateIntentMessage {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_IntentMessage); ok {
			return x.IntentMessage
		}
	}
	return nil
}

func (x *ClientEvent) GetGameJoin() *ClientGameJoin {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_GameJoin); ok {
			return x.GameJoin
		}
	}
	return nil
}

func (x *ClientEvent) GetGameExit() *ClientGameExit {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_GameExit); ok {
			return x.GameExit
		}
	}
	return nil
}

type isClientEvent_Event interface {
	isClientEvent_Event()
}

type ClientEvent_IntentMessage struct {
	IntentMessage *StateIntentMessage `protobuf:"bytes,1,opt,name=intent_message,json=intentMessage,proto3,oneof"`
}

type ClientEvent_GameJoin struct {
	GameJoin *ClientGameJoin `protobuf:"bytes,2,opt,name=game_join,json=gameJoin,proto3,oneof"`
}

type ClientEvent_GameExit struct {
	GameExit *ClientGameExit `protobuf:"bytes,3,opt,name=game_exit,json=gameExit,proto3,oneof"`
}

func (*ClientEvent_IntentMessage) isClientEvent_Event() {}

func (*ClientEvent_GameJoin) isClientEvent_Event() {}

func (*ClientEvent_GameExit) isClientEvent_Event() {}

type StateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerState   []*PlayerState         `protobuf:"bytes,1,rep,name=player_state,json=playerState,proto3" json:"player_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	mi := &file_protos_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_protos_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_protos_game_proto_rawDescGZIP(), []int{7}
}

func (x *StateSnapshot) GetPlayerState() []*PlayerState {
	if x != nil {
		return x.PlayerState
	}
	return nil
}

type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_PlayerState
	//	*ServerEvent_GameJoin
	//	*ServerEvent_GameExit
	//	*ServerEvent_Snapshot
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_protos_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_protos_game_proto_rawDescGZIP(), []int{8}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetPlayerState() *PlayerState {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_PlayerState); ok {
			return x.PlayerState
		}
	}
	return nil
}

func (x *ServerEvent) GetGameJoin() *ServerGameJoin {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_GameJoin); ok {
			return x.GameJoin
		}
	}
	return nil
}

func (x *ServerEvent) GetGameExit() *ServerGameExit {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_GameExit); ok {
			return x.GameExit
		}
	}
	return nil
}

func (x *ServerEvent) GetSnapshot() *StateSnapshot {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_PlayerState struct {
	PlayerState *PlayerState `protobuf:"bytes,1,opt,name=player_state,json=playerState,proto3,oneof"`
}

type ServerEvent_GameJoin struct {
	GameJoin *ServerGameJoin `protobuf:"bytes,2,opt,name=game_join,json=gameJoin,proto3,oneof"`
}

type ServerEvent_GameExit struct {
	GameExit *ServerGameExit `protobuf:"bytes,3,opt,name=game_exit,json=gameExit,proto3,oneof"`
}

type ServerEvent_Snapshot struct {
	Snapshot *StateSnapshot `protobuf:"bytes,4,opt,name=snapshot,proto3,oneof"`
}

func (*ServerEvent_PlayerState) isServerEvent_Event() {}

func (*ServerEvent_GameJoin) isServerEvent_Event() {}

func (*ServerEvent_GameExit) isServerEvent_Event() {}

func (*ServerEvent_Snapshot) isServerEvent_Event() {}

type ClientQueueJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientQueueJoin) Reset() {
	*x = ClientQueueJoin{}
	mi := &file_protos_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientQueueJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientQueueJoin) ProtoMessage() {}

func (x *ClientQueueJoin) ProtoReflect() protoreflect.Message {
	mi := &file_protos_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientQueueJoin.ProtoReflect.Descriptor instead.
func (*ClientQueueJoin) Descriptor() ([]byte, []int) {
	return file_protos_game_proto_rawDescGZIP(), []int{9}
}

type MatchMakingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ServerAddress string                 `protobuf:"bytes,2,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchMakingResponse) Reset() {
	*x = MatchMakingResponse{}
	mi := &file_protos_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchMakingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchMakingResponse) ProtoMessage() {}

func (x *MatchMakingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchMakingResponse.ProtoReflect.Descriptor instead.
func (*MatchMakingResponse) Descriptor() ([]byte, []int) {
	return file_protos_game_proto_rawDescGZIP(), []int{10}
}

func (x *MatchMakingResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MatchMakingResponse) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

var File_protos_game_proto protoreflect.FileDescriptor

const file_protos_game_proto_rawDesc = "" +
	"\n" +
	"\x11protos/game.proto\x12\x06server\"Q\n" +
	"\x12StateIntentMessage\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x0e\n" +
	"\x02dx\x18\x02 \x01(\x05R\x02dx\x12\x0e\n" +
	"\x02dy\x18\x03 \x01(\x05R\x02dy\"F\n" +
	"\vPlayerState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"-\n" +
	"\x0eClientGameJoin\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"H\n" +
	"\x0eServerGameJoin\x126\n" +
	"\fplayer_state\x18\x01 \x01(\v2\x13.server.PlayerStateR\vplayerState\"-\n" +
	"\x0eServerGameExit\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"\x10\n" +
	"\x0eClientGameExit\"\xc9\x01\n" +
	"\vClientEvent\x12C\n" +
	"\x0eintent_message\x18\x01 \x01(\v2\x1a.server.StateIntentMessageH\x00R\rintentMessage\x125\n" +
	"\tgame_join\x18\x02 \x01(\v2\x16.server.ClientGameJoinH\x00R\bgameJoin\x125\n" +
	"\tgame_exit\x18\x03 \x01(\v2\x16.server.ClientGameExitH\x00R\bgameExitB\a\n" +
	"\x05event\"G\n" +
	"\rStateSnapshot\x126\n" +
	"\fplayer_state\x18\x01 \x03(\v2\x13.server.PlayerStateR\vplayerState\"\xf3\x01\n" +
	"\vServerEvent\x128\n" +
	"\fplayer_state\x18\x01 \x01(\v2\x13.server.PlayerStateH\x00R\vplayerState\x125\n" +
	"\tgame_join\x18\x02 \x01(\v2\x16.server.ServerGameJoinH\x00R\bgameJoin\x125\n" +
	"\tgame_exit\x18\x03 \x01(\v2\x16.server.ServerGameExitH\x00R\bgameExit\x123\n" +
	"\bsnapshot\x18\x04 \x01(\v2\x15.server.StateSnapshotH\x00R\bsnapshotB\a\n" +
	"\x05event\"\x11\n" +
	"\x0fClientQueueJoin\"Y\n" +
	"\x13MatchMakingResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12%\n" +
	"\x0eserver_address\x18\x02 \x01(\tR\rserverAddress2F\n" +
	"\vGameService\x127\n" +
	"\aConnect\x12\x13.server.ClientEvent\x1a\x13.server.ServerEvent(\x010\x012U\n" +
	"\x12MatchMakingService\x12?\n" +
	"\aConnect\x12\x17.server.ClientQueueJoin\x1a\x1b.server.MatchMakingResponseB\x15Z\x13game-backend/protosb\x06proto3"

var (
	file_protos_game_proto_rawDescOnce sync.Once
	file_protos_game_proto_rawDescData []byte
)

func file_protos_game_proto_rawDescGZIP() []byte {
	file_protos_game_proto_rawDescOnce.Do(func() {
		file_protos_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_game_proto_rawDesc), len(file_protos_game_proto_rawDesc)))
	})
	return file_protos_game_proto_rawDescData
}

var file_protos_game_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protos_game_proto_goTypes = []any{
	(*StateIntentMessage)(nil),  // 0: server.StateIntentMessage
	(*PlayerState)(nil),         // 1: server.PlayerState
	(*ClientGameJoin)(nil),      // 2: server.ClientGameJoin
	(*ServerGameJoin)(nil),      // 3: server.ServerGameJoin
	(*ServerGameExit)(nil),      // 4: server.ServerGameExit
	(*ClientGameExit)(nil),      // 5: server.ClientGameExit
	(*ClientEvent)(nil),         // 6: server.ClientEvent
	(*StateSnapshot)(nil),       // 7: server.StateSnapshot
	(*ServerEvent)(nil),         // 8: server.ServerEvent
	(*ClientQueueJoin)(nil),     // 9: server.ClientQueueJoin
	(*MatchMakingResponse)(nil), // 10: server.MatchMakingResponse
}
var file_protos_game_proto_depIdxs = []int32{
	1,  // 0: server.ServerGameJoin.player_state:type_name -> server.PlayerState
	0,  // 1: server.ClientEvent.intent_message:type_name -> server.StateIntentMessage
	2,  // 2: server.ClientEvent.game_join:type_name -> server.ClientGameJoin
	5,  // 3: server.ClientEvent.game_exit:type_name -> server.ClientGameExit
	1,  // 4: server.StateSnapshot.player_state:type_name -> server.PlayerState
	1,  // 5: server.ServerEvent.player_state:type_name -> server.PlayerState
	3,  // 6: server.ServerEvent.game_join:type_name -> server.ServerGameJoin
	4,  // 7: server.ServerEvent.game_exit:type_name -> server.ServerGameExit
	7,  // 8: server.ServerEvent.snapshot:type_name -> server.StateSnapshot
	6,  // 9: server.GameService.Connect:input_type -> server.ClientEvent
	9,  // 10: server.MatchMakingService.Connect:input_type -> server.ClientQueueJoin
	8,  // 11: server.GameService.Connect:output_type -> server.ServerEvent
	10, // 12: server.MatchMakingService.Connect:output_type -> server.MatchMakingResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_protos_game_proto_init() }
func file_protos_game_proto_init() {
	if File_protos_game_proto != nil {
		return
	}
	file_protos_game_proto_msgTypes[6].OneofWrappers = []any{
		(*ClientEvent_IntentMessage)(nil),
		(*ClientEvent_GameJoin)(nil),
		(*ClientEvent_GameExit)(nil),
	}
	file_protos_game_proto_msgTypes[8].OneofWrappers = []any{
		(*ServerEvent_PlayerState)(nil),
		(*ServerEvent_GameJoin)(nil),
		(*ServerEvent_GameExit)(nil),
		(*ServerEvent_Snapshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_game_proto_rawDesc), len(file_protos_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protos_game_proto_goTypes,
		DependencyIndexes: file_protos_game_proto_depIdxs,
		MessageInfos:      file_protos_game_proto_msgTypes,
	}.Build()
	File_protos_game_proto = out.File
	file_protos_game_proto_goTypes = nil
	file_protos_game_proto_depIdxs = nil
}
